# HXLOS Cloud Storage - 默认配置文件
# 只包含各环境通用的基础配置，不包含敏感信息和环境差异

# 应用基础信息（通用）
app:
  name: "cloudpan"
  version: "1.0.0"
  
# 服务器通用配置
server:
  read_timeout: 60s
  write_timeout: 60s
  max_header_bytes: 1048576  # 1MB

# 数据库通用配置（非敏感部分）
database:
  mysql:
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
    conn_max_idle_time: 1800s
    timezone: "Asia/Shanghai"
    
# Redis通用配置（非敏感部分）
redis:
  protocol: 3  # RESP3协议
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# JWT通用配置（非敏感部分）
jwt:
  expire_hours: 24
  refresh_expire_hours: 168  # 7天
  issuer: "cloudpan"
  
# 文件存储通用配置
storage:
  local:
    max_size: 5368709120  # 5GB
    allowed_types: 
      - "image/jpeg"
      - "image/png"
      - "image/gif"
      - "image/webp"
      - "text/plain"
      - "application/pdf"
      - "application/zip"
      - "application/msword"
      - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      - "application/vnd.ms-excel"
      - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  oss:
    secure: true
    auto_switch_size: 104857600  # 100MB自动切换到OSS

# 用户业务规则配置（通用）
user:
  default_quota: 10737418240  # 10GB
  max_quota: 107374182400     # 100GB
  avatar:
    max_size: 5242880  # 5MB
    allowed_types:
      - "image/jpeg"
      - "image/png"
      - "image/gif"
      - "image/webp"
    path_template: "/storage/user-{user_id}/avatars/"
    filename_template: "avatar_{timestamp}.{ext}"
  password:
    min_length: 8
    max_length: 32
    require_number: true
    require_letter: true
    require_special: false
    bcrypt_cost: 12

# 邮件通用配置（非敏感部分）
email:
  smtp:
    port: 587
    from_name: "HXLOS Cloud Storage"
  templates:
    verify_code: "verify_code.html"
    password_reset: "password_reset.html"
    welcome: "welcome.html"
  verify_code:
    length: 6
    expire_minutes: 10
    max_attempts: 5

# 日志系统配置
log:
  level: "info"
  format: "json"    # json/console
  output: "both"    # file/console/both
  file_path: "logs/app.log"
  max_size: 100      # MB
  max_age: 30        # days
  max_backups: 5     # files
  compress: true
  access_log:
    enabled: true
    file_path: "logs/access.log"
    format: "json"

# 安全通用配置
security:
  cors:
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allow_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    expose_headers:
      - "Content-Length"
    allow_credentials: true
    max_age: 86400  # 24小时
  rate_limit:
    requests_per_minute: 60
    burst: 100
    
# 缓存通用配置
cache:
  default_ttl: 3600s  # 1小时
  user_info_ttl: 1800s  # 30分钟
  file_info_ttl: 600s   # 10分钟
  verification_code_ttl: 600s  # 10分钟
  
# 消息队列通用配置
queue:
  redis_stream:
    streams:
      file_upload: "cloudpan:file:upload"
      file_scan: "cloudpan:file:scan"
      email_send: "cloudpan:email:send"
      user_action: "cloudpan:user:action"
    consumer_group: "cloudpan-workers"
    
# WebSocket通用配置
websocket:
  path: "/ws"
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  read_deadline: 60s
  write_deadline: 10s
  ping_period: 54s
  pong_wait: 60s
  max_message_size: 1048576  # 1MB

# 监控通用配置
monitoring:
  metrics:
    path: "/metrics"
  health:
    path: "/health"
  pprof:
    path: "/debug/pprof"

# 国际化通用配置
i18n:
  default_language: "zh-CN"
  languages:
    - "zh-CN"
    - "en-US"
  path: "./i18n"